<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="cs" lang="cs">
<head>
    <base href="http://{$_SERVER['SERVER_NAME']}{$baseUri}" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta http-equiv="Content-Language" content="cs" />

	<title>Test</title>

	<link rel="stylesheet" media="screen,projection,tv" href="{$baseUri}css/screen.css" type="text/css" />
    <link rel="stylesheet" media="screen,projection,tv" href="{$baseUri}css/suggest.css" type="text/css" />
    <script src="http://code.jquery.com/jquery-1.4.2.min.js" type="text/javascript"></script>    
    <script src="{$baseUri}js/jquery.dimensions.js" type="text/javascript"></script>
    <script src="{$baseUri}js/jquery.bgiframe.min.js" type="text/javascript"></script>
    <script src="{$baseUri}js/jquery.suggest.js" type="text/javascript"></script>
</head>

<body>      
    @{include $content}
</body>

</html>
